# build environment
FROM node:13.12.0-alpine as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm install
RUN npm ci --only=production

COPY . ./

EXPOSE 8082
CMD ["node", "src/index.js"]





