FROM mongo
COPY ./data/users.json /users.json
CMD mongoimport\
    --username ${MONGO_INITDB_ROOT_USERNAME}\
    --password ${MONGO_INITDB_ROOT_PASSWORD}\
    --host 127.0.0.1\
    --db asg2\
    --collection users\
    --type json\
    --file /users.json\
    --jsonArray

COPY ./data/plays-nested.json /plays.json
CMD mongoimport\
    --username ${MONGO_INITDB_ROOT_USERNAME}\
    --password ${MONGO_INITDB_ROOT_PASSWORD}\
    --host 127.0.0.1\
    --db asg2\
    --collection plays\
    --type json\
    --file /plays.json\
    --jsonArray
EXPOSE 27017
CMD ["mongod"]
